name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Build EXE
        run: npm run dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lavajato-exe
          path: dist
          "build": {
  "appId": "com.lavajato.app",
  "productName": "LavaJato Pro",
  "files": [
    "dist/**/*",
    "electron/**/*",
    "package.json"
  ],
  "win": {
    "target": "nsis"
  }
}
